# Definindo os componontes da imagem docker e definindo porta exposta
FROM ubuntu

# --- Definindo Diretorio padrao de trabalho
WORKDIR /app
COPY --chown=root:root --chmod=100 ./entrypoint.sh .
ENTRYPOINT [ "./entrypoint.sh" ]
# Passando parametro padrao via CMD
CMD [ "XPTO" ]

# --- Comandos para iniciar
# sudo docker build -t ubuntu-curl .
# sudo docker inspect ubuntu-curl
# docker container run ubuntu-curl  

# Variaveis podem ser sobrescritas ao passar parametros no docker build, assim como o CMD e ENTRYPOINT 